logging.level.com.jvmd.digitalurpaq_ai_agent=DEBUG
logging.level.org.springframework.data.elasticsearch=DEBUG
logging.level.org.springframework.web.reactive=DEBUG
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
app.rate-limit.requests-per-minute=100
springdoc.swagger-ui.enabled=true
